### To set the IOC to boot from here
# and to set the startup script type
# the following command in this directory.
# make ST=st.cmd

TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86
TARGETS = envPaths

include $(TOP)/configure/RULES.ioc
